version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=false
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080