on:
    name: Continuous Deployment
  push:
    branches: [ main ]

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_CONTAINER_REGISTRY: "avaContainerRegistory"
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_NAME: "ava-app"
  CONTAINER_APP_NAME: "my-ava-container-app"
  RESOURCE_GROUP: "ava-ai-sales-assistant-rg"
  CONTAINER_APP_ENVIRONMENT: "ava-container-app-env"
  LOG_ANALYTICS_WORKSPACE: "workspace-avaaisalesassistantrgKeNt"
  BLOB_URL: ${{ secrets.BLOB_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to Azure Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: 'Build and push image to ACR'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest
          cache-to: type=inline

      - name: 'Deploy to Azure Container App'
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ env.AZURE_CONTAINER_REGISTRY }}
          acrUsername: ${{ env.REGISTRY_USERNAME }}
          acrPassword: ${{ env.REGISTRY_PASSWORD }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT }}
          logAnalyticsWorkspace: ${{ env.LOG_ANALYTICS_WORKSPACE }}
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          environmentVariables: |
            BLOB_URL=${{ secrets.BLOB_URL }}
            ENVIRONMENT=production

      - name: 'Azure logout'
        run: |
          az logout