name: Continuous Deployment

on:
  push:
    branches: [ main ]

env:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
    REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
    REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    CONTAINER_APP_NAME: ${{ secrets.CONTAINER_APP_NAME }}
    RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
    BLOB_URL: ${{ secrets.BLOB_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: 'Build and push image to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

    - name: 'Deploy to Azure Container App'
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.AZURE_CONTAINER_REGISTRY }}
        acrUsername: ${{ env.REGISTRY_USERNAME }}
        acrPassword: ${{ env.REGISTRY_PASSWORD }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        environmentVariables: |
          BLOB_URL=${{ secrets.BLOB_URL }}
          ENVIRONMENT=production

    - name: 'Azure logout'
      run: |
        az logout